## Importing Libraries

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

## Data Preprocessing

### Training Set Preprocessing

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    "/Users/aditya/Desktop/Repositories/MinorProject-1/Dataset/train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


### Validation Set Preprocessing

In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "/Users/aditya/Desktop/Repositories/MinorProject-1/Dataset/val",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [4]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [10]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 47.    49.    61.  ]
   [ 41.75  44.    55.25]
   [ 40.5   43.5   52.5 ]
   ...
   [108.5  111.5  120.5 ]
   [109.75 112.75 121.75]
   [109.25 112.25 121.25]]

  [[ 65.75  68.75  77.75]
   [ 43.    46.    54.5 ]
   [ 51.75  54.75  62.25]
   ...
   [107.   110.   119.  ]
   [105.75 108.75 117.75]
   [109.25 112.25 121.25]]

  [[ 53.    53.    61.  ]
   [ 53.25  53.5   60.75]
   [ 59.25  60.    65.75]
   ...
   [109.5  112.5  121.5 ]
   [107.25 110.25 119.25]
   [106.   109.   118.  ]]

  ...

  [[ 76.5   98.5   95.5 ]
   [ 70.75  92.75  89.75]
   [ 83.   105.   102.  ]
   ...
   [195.25 193.25 196.25]
   [188.5  186.5  189.5 ]
   [187.   185.   188.  ]]

  [[ 75.75  97.75  94.75]
   [ 68.75  90.75  87.75]
   [ 82.25 104.25 101.25]
   ...
   [185.5  183.5  186.5 ]
   [188.25 186.25 189.25]
   [191.75 189.75 192.75]]

  [[ 71.25  93.25  90.25]
   [ 71.    93.    90.  ]
   [ 79.25 101.25  98.25]
   ...
   [186.25 184.25 187.25]
   [179.75 177.75 180.75]
   [182.   180.   18

## Building Model

In [5]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten
from tensorflow.keras.models import Sequential

In [6]:
model = Sequential()

### Building Convolution Layer

In [7]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

/Users/aditya/.pyenv/versions/minorproject-env/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [9]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [10]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Flatten())
model.add(Dense(units=1500,activation ='relu'))

### Output Layer

In [12]:
model.add(Dense(units=38,activation='softmax'))

## Compiling Model

In [13]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 32, 32, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 16, 16, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 16, 16, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 8, 8, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │    16,778,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        38,950 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,989,446 (68.62 MB)

 Trainable params: 17,989,446 (68.62 MB)

 Non-trainable params: 0 (0.00 B)

## Model Training

In [15]:
training_history = model.fit(x=training_set,validation_data = validation_set, epochs = 10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1623s 739ms/step - accuracy: 0.6581 - loss: 1.1953 - val_accuracy: 0.8214 - val_loss: 0.5740
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2010s 915ms/step - accuracy: 0.8826 - loss: 0.3566 - val_accuracy: 0.8916 - val_loss: 0.3465
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1960s 892ms/step - accuracy: 0.9183 - loss: 0.2460 - val_accuracy: 0.9067 - val_loss: 0.2925
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1908s 868ms/step - accuracy: 0.9369 - loss: 0.1912 - val_accuracy: 0.9120 - val_loss: 0.2818
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1910s 870ms/step - accuracy: 0.9450 - loss: 0.1656 - val_accuracy: 0.9278 - val_loss: 0.2495
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1902s 866ms/step - accuracy: 0.9512 - loss: 0.1453 - val_accuracy: 0.9204 - val_loss: 0.3045
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1906s 868ms/step - accuracy: 0.9566 - loss: 0.1334 - val_accuracy: 0.9127 - val_loss: 0.3197
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1897s 864ms/s

## Model Evaluation

In [16]:
train_loss, train_acc = model.evaluate(training_set)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 334s 152ms/step - accuracy: 0.9763 - loss: 0.0753


In [17]:
print(train_loss,train_acc)

0.0753072127699852 0.9763425588607788


In [18]:
val_loss, val_acc = model.evaluate(validation_set)

550/550 ━━━━━━━━━━━━━━━━━━━━ 75s 136ms/step - accuracy: 0.9276 - loss: 0.2732


In [19]:
print(val_loss,val_acc)

0.2732119858264923 0.9276121258735657


## Saving Model

In [20]:
model.save("trained_model.h5")

In [21]:
model.save("trained_model.keras")

In [22]:
training_history.history

{'accuracy': [0.6580695509910583,
  0.8825520873069763,
  0.918258786201477,
  0.9368945360183716,
  0.9450316429138184,
  0.9512198567390442,
  0.9565829634666443,
  0.9584749937057495,
  0.9629418849945068,
  0.9630272388458252],
 'loss': [1.1952650547027588,
  0.3566458523273468,
  0.24601495265960693,
  0.19119951128959656,
  0.16560658812522888,
  0.14525125920772552,
  0.1334109753370285,
  0.1277962028980255,
  0.1157444566488266,
  0.11593928933143616],
 'val_accuracy': [0.8213635087013245,
  0.8916457891464233,
  0.9066696763038635,
  0.9120191335678101,
  0.9278397560119629,
  0.9204416275024414,
  0.9127020239830017,
  0.9243113994598389,
  0.9074664115905762,
  0.9276121258735657],
 'val_loss': [0.5740385055541992,
  0.3464682996273041,
  0.2925010621547699,
  0.28181877732276917,
  0.24953889846801758,
  0.30446138978004456,
  0.31967395544052124,
  0.28244367241859436,
  0.3639041483402252,
  0.2732117474079132]}

In [6]:
class_name = validation_set.class_names
class_name

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_