## Importing Libraries

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

## Data Preprocessing

### Training Set Preprocessing

In [7]:
training_set = tf.keras.utils.image_dataset_from_directory(
    "/Users/aditya/Desktop/Repositories/MinorProject-1/Dataset/train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


### Validation Set Preprocessing

In [8]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "/Users/aditya/Desktop/Repositories/MinorProject-1/Dataset/val",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [9]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [10]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 47.    49.    61.  ]
   [ 41.75  44.    55.25]
   [ 40.5   43.5   52.5 ]
   ...
   [108.5  111.5  120.5 ]
   [109.75 112.75 121.75]
   [109.25 112.25 121.25]]

  [[ 65.75  68.75  77.75]
   [ 43.    46.    54.5 ]
   [ 51.75  54.75  62.25]
   ...
   [107.   110.   119.  ]
   [105.75 108.75 117.75]
   [109.25 112.25 121.25]]

  [[ 53.    53.    61.  ]
   [ 53.25  53.5   60.75]
   [ 59.25  60.    65.75]
   ...
   [109.5  112.5  121.5 ]
   [107.25 110.25 119.25]
   [106.   109.   118.  ]]

  ...

  [[ 76.5   98.5   95.5 ]
   [ 70.75  92.75  89.75]
   [ 83.   105.   102.  ]
   ...
   [195.25 193.25 196.25]
   [188.5  186.5  189.5 ]
   [187.   185.   188.  ]]

  [[ 75.75  97.75  94.75]
   [ 68.75  90.75  87.75]
   [ 82.25 104.25 101.25]
   ...
   [185.5  183.5  186.5 ]
   [188.25 186.25 189.25]
   [191.75 189.75 192.75]]

  [[ 71.25  93.25  90.25]
   [ 71.    93.    90.  ]
   [ 79.25 101.25  98.25]
   ...
   [186.25 184.25 187.25]
   [179.75 177.75 180.75]
   [182.   180.   18

## Building Model

In [24]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten
from tensorflow.keras.models import Sequential

In [12]:
model = Sequential()

### Building Convolution Layer

In [16]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [17]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [19]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [25]:
model.add(Flatten())
model.add(Dense(units=1024,activation ='relu'))

### Output Layer

In [27]:
model.add(Dense(units=38,activation='softmax'))

## Compiling Model

In [29]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [30]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 32, 32, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 32, 32, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 16, 16, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 16, 16, 256)    │       147,712 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 16, 16, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 8, 8, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │    16,778,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        38,950 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,712,902 (67.57 MB)

 Trainable params: 17,712,902 (67.57 MB)

 Non-trainable params: 0 (0.00 B)

## Model Training

In [ ]:
training_history = model.fit(x=training_set,validation_data = validation_set, epochs = 10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2142s 975ms/step - accuracy: 0.6273 - loss: 1.2552 - val_accuracy: 0.7932 - val_loss: 0.6351
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2615s 1s/step - accuracy: 0.8497 - loss: 0.4598 - val_accuracy: 0.8685 - val_loss: 0.3980
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2821s 1s/step - accuracy: 0.8952 - loss: 0.3161 - val_accuracy: 0.8636 - val_loss: 0.4325
Epoch 4/10
 215/2197 ━━━━━━━━━━━━━━━━━━━━ 43:35 1s/step - accuracy: 0.9101 - loss: 0.2691